<?php
if ($this->isEnabled()) {
	$button_width = Mage::getStoreConfig("checkout/internationalcheckout/ic_button_width");
	if($button_width == ''){$button_width = '200';}
	if(stripos(Mage::getBaseUrl(), 'https')){
		$url = Mage::getBaseUrl();
	}else{
		$url = str_replace('http', 'https', Mage::getBaseUrl());		
	}
	
?>
<form name="icForm" id="icForm" method="post" action="<?php echo $url.'index.php/internationalcheckout';?>">
	<button style="width:<?php echo $button_width; ?>px; padding:0px;cursor:pointer;" title="<?php echo $this->__('International Checkout') ?>" class="<?php echo $this->buttonClassName(); ?>" <?php echo $this->buttonImagePath(); ?> type="submit">
    	<span style="cursor:pointer;">
        	<span >
				<?php echo $this->buttonText(); ?>
            </span>
        </span>
    </button>
    <br />	
    <div align="right" style="font-size:11px;float:right">
    	<div style="width:<?php echo $button_width; ?>px;margin-bottom:10px;text-align:center">
			<?php echo $this->textBelowButton(); ?>
        </div>
    </div>
</form>
<?php
	} // isEnabled	
?>

